#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_offset_defaults.py

��� vergiliusproject.com / WinDbg "dt" / IDA ��������ת�����ɵ� JSON ƫ�����ݣ�
����Ϊ MyDriver64\\OffsetDefaults.c ��ʹ�õ� C ��ͬ�ļ� (.inc) Ƭ�ε��γ̡�

�����ʽ��һ�� JSON ��������ʵ�ʣ�
[
  {
    "build": 19045,
    "module": "ntoskrnl",
    "struct": "_EPROCESS",
    "fields": {
      "UniqueProcessId": 1088,
      "ActiveProcessLinks": 1096,
      "ImageFileName": 1448
    },
    "size": 4416
  },
  {
    "build": 19045,
    "module": "ntoskrnl",
    "struct": "_ETHREAD",
    "fields": { "Cid.UniqueThread": 1208 }
  },
  ...
  {
    "build": 19045,
    "module": "ntoskrnl",
    "globals": {
      "PsActiveProcessHead": 8916576,
      "PspCidTable":        7012880
    }
  }
]

����������Դ�����ݣ�
  - vergiliusproject.com (����ҳ��ͨ�����ƽ��) -- �������Ƹ� JSON
  - WinDbg �Է��ŷ�����: dt -v nt!_EPROCESS  ?? offsetof(_EPROCESS, ...)
  - Volatility 3 �ٷ� ISF (���γ��� Microsoft ��ʽ PDB) https://isf-server.techanarchy.net/data/windows/

������
  python tools\\gen_offset_defaults.py vergilius.json --build 19045 --var g_Tbl_19045 \\
        > MyDriver64\\OffsetDefaults.generated.inc

֮���� OffsetDefaults.c ��� #include "OffsetDefaults.generated.inc",
����ֱ�ӽ� ��ӡ�����������������е����ݡ�

�ű���������������ʱ�����κ�����, ֻ�����ı���
"""

import argparse
import json
import sys
from typing import Any, Dict, Iterable, List, Tuple


def emit_struct_offsets(rows: Iterable[Dict[str, Any]], symbol: str) -> str:
    lines: List[str] = []
    lines.append(f"static const OFFSET_ENTRY {symbol}_NtStruct[] = {{")
    for r in rows:
        s = r["struct"]
        for m, off in r.get("fields", {}).items():
            lines.append(f'    {{ L"{s}", L"{m}", 0x{int(off):X} }},')
    lines.append("    { NULL, NULL, -1 }")
    lines.append("};")
    return "\n".join(lines)


def emit_struct_sizes(rows: Iterable[Dict[str, Any]], symbol: str) -> str:
    lines: List[str] = []
    lines.append(f"static const SIZE_ENTRY {symbol}_NtSize[] = {{")
    for r in rows:
        if "size" in r:
            lines.append(f'    {{ L"{r["struct"]}", 0x{int(r["size"]):X} }},')
    lines.append("    { NULL, -1 }")
    lines.append("};")
    return "\n".join(lines)


def emit_globals(rows: Iterable[Dict[str, Any]], symbol: str) -> str:
    lines: List[str] = []
    lines.append(f"static const GLOBAL_ENTRY {symbol}_NtGlobal[] = {{")
    for r in rows:
        for name, off in r.get("globals", {}).items():
            lines.append(f'    {{ L"{name}", 0x{int(off):X} }},')
    lines.append("    { NULL, -1 }")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate C offset tables from vergilius-style JSON.")
    ap.add_argument("input", help="path to input JSON file (or '-' for stdin)")
    ap.add_argument("--build", type=int, required=True, help="Windows build number, e.g. 19045")
    ap.add_argument("--var", default=None, help="C variable prefix (default: g_Tbl_<build>)")
    args = ap.parse_args()

    raw = sys.stdin.read() if args.input == "-" else open(args.input, "r", encoding="utf-8").read()
    data = json.loads(raw)

    if not isinstance(data, list):
        print("error: input JSON must be a list", file=sys.stderr)
        return 1

    rows = [r for r in data if int(r.get("build", -1)) == args.build]
    if not rows:
        print(f"error: no entries for build {args.build}", file=sys.stderr)
        return 1

    prefix = args.var or f"g_Tbl_{args.build}"

    print(f"// auto-generated by tools/gen_offset_defaults.py, build {args.build}")
    print(f"// DO NOT EDIT BY HAND. Re-run the scraper + generator to refresh.")
    print()
    print(emit_struct_offsets(rows, prefix))
    print()
    print(emit_struct_sizes(rows, prefix))
    print()
    print(emit_globals(rows, prefix))
    return 0


if __name__ == "__main__":
    sys.exit(main())
